apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kube-shield.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-shield.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "kube-shield.selectorLabels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "kube-shield.serviceAccountName" . }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: kube-shield
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - scan
                - --output
                - "{{ .Values.output }}"
                - --severity
                - "{{ .Values.severity }}"
                {{- if .Values.scanners }}
                - --scanners
                - "{{ join "," .Values.scanners }}"
                {{- end }}
                {{- if .Values.readSecretData }}
                - --read-secret-data
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
