apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-shield.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-shield.labels" . | nindent 4 }}
