replicaCount: 1

image:
  repository: ghcr.io/ramazankara/kube-shield
  pullPolicy: IfNotPresent
  tag: ""

schedule: "0 */6 * * *"  # Every 6 hours

scanners:
  - workload
  - cis
  - rbac
  - netpol
  - secrets

severity: low
output: json

serviceAccount:
  create: true
  name: kube-shield

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
