//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/RamazanKara/kube-shield/internal/scanner"
	"github.com/RamazanKara/kube-shield/internal/scanner/engine"
)

// repoRoot walks up from the current working directory to the module root
// (the directory containing go.mod) so the generator is independent of the
// directory `go generate` runs it from.
func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return "."
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "."
		}
		dir = parent
	}
}

func main() {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by go generate; DO NOT EDIT. -->\n\n")
	buf.WriteString("# Scanner Reference\n\n")
	buf.WriteString("This reference is generated from kube-shield's built-in rule catalog. Use it to understand rule intent, data access, expected false positives, and documentation that must stay stable for CI and SARIF consumers.\n\n")
	buf.WriteString("Scanner results are posture signals, not a full Kubernetes audit. kube-shield focuses on API-visible misconfigurations that can be checked consistently from a Kubernetes client.\n\n")

	buf.WriteString("| Scanner | Checks | Category | Severity Range |\n")
	buf.WriteString("|---------|--------|----------|----------------|\n")
	for _, def := range scanner.BuiltIns() {
		fmt.Fprintf(&buf, "| `%s` | %d | `%s` | %s |\n", def.Name, len(engine.RulesByScanner(def.Name)), def.Category, def.SeverityRange)
	}
	buf.WriteString("\n")

	buf.WriteString("## Severity Levels\n\n")
	buf.WriteString("| Level | Meaning |\n")
	buf.WriteString("|-------|---------|\n")
	buf.WriteString("| Critical | Direct compromise or full cluster-control path is plausible |\n")
	buf.WriteString("| High | Significant security weakness or strong escalation path |\n")
	buf.WriteString("| Medium | Defense-in-depth gap or risky configuration |\n")
	buf.WriteString("| Low | Best-practice deviation |\n")
	buf.WriteString("| Info | Operational observation |\n\n")
	buf.WriteString("Severity is assigned by expected blast radius and exploitability. If a finding depends heavily on local policy or compensating controls, prefer the lower severity and explain the risk clearly in remediation text.\n\n")

	for _, def := range scanner.BuiltIns() {
		writeScannerSection(&buf, def)
	}

	buf.WriteString("## Scoring\n\n")
	buf.WriteString("The score is calculated from the filtered, de-duplicated finding set:\n\n")
	buf.WriteString("```text\n")
	buf.WriteString("score = 100 - (critical*10 + high*5 + medium*2 + low*0.5)\n")
	buf.WriteString("```\n\n")
	buf.WriteString("Info findings do not reduce the score. Scores are clamped at zero. Known CIS/core overlaps are counted once in the summary; raw findings remain in JSON and SARIF output.\n\n")
	buf.WriteString("| Score | Grade |\n")
	buf.WriteString("|-------|-------|\n")
	buf.WriteString("| 90-100 | A |\n")
	buf.WriteString("| 80-89 | B |\n")
	buf.WriteString("| 70-79 | C |\n")
	buf.WriteString("| 60-69 | D |\n")
	buf.WriteString("| 0-59 | F |\n\n")

	buf.WriteString("## Documentation Maintenance\n\n")
	buf.WriteString("When adding, removing, or changing a check:\n\n")
	buf.WriteString("- Keep `CheckID` stable unless the behavior is intentionally replaced.\n")
	buf.WriteString("- Update the rule catalog in `internal/scanner/engine/rules.go`.\n")
	buf.WriteString("- Run `go generate ./...` to refresh this file.\n")
	buf.WriteString("- Update README scanner counts when counts change.\n")
	buf.WriteString("- Add or update unit tests and E2E fixtures.\n")
	buf.WriteString("- Include the behavior change in `CHANGELOG.md`.\n")
	buf.WriteString("- Keep titles short enough to scan in table, JSON, SARIF, and TUI output.\n")

	out := filepath.Join(repoRoot(), "docs", "reference", "scanners.md")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func writeScannerSection(buf *bytes.Buffer, def scanner.Definition) {
	rules := engine.RulesByScanner(def.Name)
	fmt.Fprintf(buf, "## %s Scanner (`%s`)\n\n", scannerTitle(def.Name), def.Name)
	fmt.Fprintf(buf, "| Check ID | Severity | Confidence | Data Access | Default | Title |\n")
	fmt.Fprintf(buf, "|----------|----------|------------|-------------|---------|-------|\n")
	for _, rule := range rules {
		fmt.Fprintf(buf, "| %s | %s | %s | `%s` | %t | %s |\n", rule.CheckID, rule.Severity, rule.Confidence, rule.DataAccess, rule.DefaultEnabled, rule.Title)
	}
	buf.WriteString("\n")

	switch def.Name {
	case "workload":
		buf.WriteString("Completed and failed pods are skipped.\n\n")
	case "cis":
		buf.WriteString("Only API-accessible CIS Kubernetes Benchmark controls are evaluated. Node filesystem, control-plane host, and managed-provider settings are outside this scanner's scope. System namespaces are skipped for namespace-scoped CIS checks.\n\n")
	case "rbac":
		buf.WriteString("Kubernetes system roles and common CNI system roles are skipped to reduce noise.\n\n")
	case "netpol":
		buf.WriteString("The scanner evaluates declared NetworkPolicy objects. It does not prove runtime dataplane enforcement by a specific CNI plugin. System namespaces are skipped.\n\n")
	case "secrets":
		buf.WriteString("Default secret checks use pod specs and metadata-only secret inventory. kube-shield does not request or print secret values by default. `SEC-010` requires `--read-secret-data` and is disabled by default.\n\n")
	}

	for _, rule := range rules {
		writeRule(buf, rule)
	}
}

func writeRule(buf *bytes.Buffer, rule engine.Rule) {
	fmt.Fprintf(buf, "<a id=\"%s\"></a>\n\n", strings.ToLower(rule.CheckID))
	fmt.Fprintf(buf, "### %s\n\n", rule.CheckID)
	fmt.Fprintf(buf, "**Title:** %s\n\n", rule.Title)
	fmt.Fprintf(buf, "**Severity:** %s\n\n", rule.Severity)
	fmt.Fprintf(buf, "**Confidence:** %s\n\n", rule.Confidence)
	fmt.Fprintf(buf, "**Data access:** `%s`\n\n", rule.DataAccess)
	fmt.Fprintf(buf, "**Default enabled:** %t\n\n", rule.DefaultEnabled)
	fmt.Fprintf(buf, "**Rationale:** %s\n\n", rule.Rationale)
	fmt.Fprintf(buf, "**Impact:** %s\n\n", rule.Impact)
	fmt.Fprintf(buf, "**Remediation:** %s\n\n", rule.Remediation)
	if rule.FalsePositives != "" {
		fmt.Fprintf(buf, "**False-positive notes:** %s\n\n", rule.FalsePositives)
	}
	if len(rule.Standards) > 0 {
		buf.WriteString("**Standards:**\n\n")
		for _, standard := range rule.Standards {
			fmt.Fprintf(buf, "- %s: %s\n", standard.Name, standard.Control)
		}
		buf.WriteString("\n")
	}
	if len(rule.References) > 0 {
		buf.WriteString("**References:**\n\n")
		for _, ref := range rule.References {
			fmt.Fprintf(buf, "- <%s>\n", ref)
		}
		buf.WriteString("\n")
	}
}

func scannerTitle(name string) string {
	switch name {
	case "cis":
		return "CIS Kubernetes Benchmark"
	case "netpol":
		return "Network Policy"
	case "rbac":
		return "RBAC"
	default:
		return strings.ToUpper(name[:1]) + name[1:]
	}
}
